# English-only master word lists for the "Sample Lists" feature in My
# Lists. Never hand-translated — core/sample_list_generator.py translates
# these into whatever language pair a user actually wants, on
# demand (once per pair per user, via Gemini), instead of the app storing
# a full 50-word translated dataset per supported language up front. This
# is the single source of truth for what each category contains; adding a
# new category means adding one more entry here, not authoring translated
# data for every language.

COMMON_WORDS = [
    "house",
    "dog",
    "cat",
    "book",
    "table",
    "chair",
    "water",
    "food",
    "school",
    "friend",
    "family",
    "car",
    "city",
    "country",
    "day",
    "night",
    "week",
    "month",
    "year",
    "money",
    "job",
    "door",
    "window",
    "street",
    "park",
    "beach",
    "mountain",
    "river",
    "sea",
    "sky",
    "sun",
    "moon",
    "star",
    "tree",
    "flower",
    "fruit",
    "phone",
    "computer",
    "music",
    "movie",
    "letter",
    "picture",
    "key",
    "clothing",
    "shoe",
    "hat",
    "shirt",
    "clock",
    "bridge",
    "garden",
]

COMMON_VERBS = [
    "to speak",
    "to eat",
    "to live",
    "to have",
    "to do",
    "to go",
    "to be",
    "to be",
    "to be able to",
    "to want",
    "to say",
    "to see",
    "to give",
    "to know",
    "to come",
    "to leave",
    "to put",
    "to think",
    "to find",
    "to arrive",
    "to happen",
    "to owe",
    "to follow",
    "to feel",
    "to return",
    "to take",
    "to know a person",
    "to carry",
    "to leave something",
    "to call",
    "to understand",
    "to ask for",
    "to receive",
    "to show",
    "to create",
    "to work",
    "to study",
    "to write",
    "to read",
    "to play",
    "to run",
    "to walk",
    "to sleep",
    "to wake up",
    "to begin",
    "to finish",
    "to open",
    "to close",
    "to buy",
    "to sell",
]

IRREGULAR_VERBS = [
    "to be",
    "to be (state/location)",
    "to have",
    "to have (auxiliary)",
    "to go",
    "to do / to make",
    "to be able to",
    "to want",
    "to know (a fact)",
    "to know (a person)",
    "to say / to tell",
    "to see",
    "to come",
    "to put",
    "to leave / to go out",
    "to sleep",
    "to feel",
    "to serve",
    "to write",
    "to read",
    "to drive",
    "to be born",
    "to die",
    "to run",
    "to drink",
    "to believe",
    "to live",
    "to follow",
    "to laugh",
    "to fear",
    "to paint",
    "to reach",
    "to resolve / to solve",
    "to sew",
    "to defeat",
    "to convince",
    "to receive",
    "to sit down",
    "to be worth",
    "to send",
    "to build",
    "to destroy",
    "to produce",
    "to translate",
    "to bring",
    "to fall",
    "to hear",
    "to choose",
    "to ask for",
    "to repeat",
]

FOOD = [
    "apple",
    "bread",
    "milk",
    "coffee",
    "egg",
    "meat",
    "fish",
    "fruit",
    "vegetable",
    "juice",
    "rice",
    "pasta",
    "cheese",
    "butter",
    "sugar",
    "salt",
    "pepper",
    "oil",
    "soup",
    "salad",
    "chicken",
    "beef",
    "pork",
    "ham",
    "sausage",
    "shrimp",
    "potato",
    "tomato",
    "onion",
    "garlic",
    "carrot",
    "lettuce",
    "banana",
    "orange",
    "lemon",
    "strawberry",
    "grape",
    "watermelon",
    "pineapple",
    "peach",
    "nut",
    "honey",
    "jam",
    "cake",
    "cookie",
    "chocolate",
    "ice cream",
    "wine",
    "beer",
    "tea",
]

SAMPLE_LIST_CATEGORIES = {
    "common_words": COMMON_WORDS,
    "common_verbs": COMMON_VERBS,
    "irregular_verbs": IRREGULAR_VERBS,
    "food": FOOD,
}

# Display label + list_type ("verb" unlocks tense selection on Generate
# Quiz) per category — used both for the bulk first-time generation
# (Settings' "what are you learning?" step) and the on-demand single-
# category catalog in My Lists. Labels are fixed English regardless of the
# app's current UI locale, since the backend has no concept of that.
SAMPLE_CATEGORY_META = {
    "common_words": ("Common Words", "vocab"),
    "common_verbs": ("Common Verbs", "verb"),
    "irregular_verbs": ("Irregular Verbs", "verb"),
    "food": ("Food", "vocab"),
}
